service: cicd-demo

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

  deploymentBucket:
    serverSideEncryption: AES256
    blockPublicAccess: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query 
        - dynamodb:GetItem 
        - dynamodb:PutItem     
        - dynamodb:UpdateItem 
        - dynamodb:DeleteItem
        - lambda:*
        - log:*
      Resource:
        - '*'
        #- arn:aws:dynamo:*account:table/name*

custom:
  pythonRequirements:
    dockerizePip: true
    dynamodb:
      stages:
        - dev
      start:
        migrate: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  add_new:
    handler: handler.lambda_handler
    timeout: 5
    events:
      - http:
          integration: lambda
          path: add_new
          cors: false
          method: post
          request:
            passThrough: NEVER

resources:
  Resources:
    Challenge:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: team
            AttributeType: S
          - AttributeName: country
            AttributeType: S
          - AttributeName: desc
            AttributeType: S
          - AttributeName: rating
            AttributeType: S
        KeySchema:
          - AttributeName: team
            KeyType: HASH
          - AttributeName: country
            KeyType: HASH
          - AttributeName: desc
            KeyType: HASH
          - AttributeName: rating
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: Challenge

